"""Migration

Revision ID: 45cb7ce5ac7c
Revises: 
Create Date: 2023-12-14 14:13:02.508780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45cb7ce5ac7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocolo_asgard',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('protocolo', sa.BIGINT, autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('cadastro', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('saec', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('valor_total', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('saldo', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='protocolo_asgard_pkey')
    )
    op.create_table('protocolo_onr',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_cadastro', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data_resposta', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('saec', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('valor', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='protocolo_onr_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protocolo_onr')
    op.drop_table('protocolo_asgard')
    # ### end Alembic commands ###


